version: "3.8"

services:
  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: "cloudbeaver"
      restart: always
      ports:
       - '8978:8978'
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace

networks:
  default:

volumes:
  cloudbeaver:
