services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "jimm0063@gmail.com"
      ZO_ROOT_USER_PASSWORD: "Transformers25!"
    ports:
      - "0.0.0.0:5080:5080"
    volumes:
      - data:/data
volumes:
  data:
